site_name: Dr. Lásaro Jonas Camargos

nav:
        - About: index.md
        - Research: publications/index.md
        - Alumni: students/index.md
        - Notes: teaching/index.md 
            #- 'Profissão em Sistemas de Informação': teaching/gsi009/index.md
            #- 'Programação Funcional': teaching/gbc033/index.md
            #- 'Sistemas Distribuídos': teaching/gbc074gsi028/index.md

theme:
        name: material #readthedocs
        language: pt
        palette:
           - scheme: default
             toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
             accent: deep orange
             primary: blue grey
           - scheme: slate
             toggle:
                icon: material/toggle-switch
                name: Switch to light mode
        features:
            - navigation.tabs
            - header.autohide
            - navigation.indexes
plugins:
        - search

markdown_extensions:
        - toc:
            toc_depth: 3
#        - mdx_math
        - admonition
        - footnotes
        - pymdownx.arithmatex:
               generic: true
        - pymdownx.betterem:
               smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
        - pymdownx.highlight:
             linenums: true
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
              custom_fences:
                   - name: mermaid
                     class: mermaid
                     format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tabbed:
            alternate_style: true
        - pymdownx.tilde
extra:
  analytics:
    provider: google
    property: G-65TK61CS8M
    
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/lasaro/
    - icon: fontawesome/brands/github
      link: https://github.com/lasarojc

extra_javascript:
        - https://unpkg.com/mermaid@10/dist/mermaid.min.js
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
