name: ci
on:
  push:
    branches:
      - source
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install python-markdown-math
      - run: mkdocs gh-deploy --force --remote-branch master
