name: ci
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      run: |
           pip install mkdocs-material
           pip install python-markdown-math

    - name: Create local changes
      run: |
           mkdir ../branch_build
           mkdocs build -d ../branch_build

    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
         ref: master
         path: master-deploy

    - name: Push changes
      run: |
        cd ../master-deploy
        cp -r ../branch_build/* .
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git commit -m "Add changes" -a
        git push

