name: ci
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: install material
      run: |
           pip install mkdocs-material
           pip install python-markdown-math

    - name: Checkout ref branch
      uses: actions/checkout@v2
      with:
         ref: source
         path: /home/runner/work/lasarojc.github.io/source-branch

    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
         ref: master
         path: /home/runner/work/lasarojc.github.io/master-branch

    - name: Create local changes and commit
      run: |
           cd /home/runner/work/lasarojc.github.io/source-branch
           mkdocs build -d //home/runner/work/lasarojc.github.io/master-branch
           cd /home/runner/work/lasarojc.github.io/master-branch
           git config --local user.email "github-actions@github.com"
           git config --local user.name "github-actions"
           git commit -m "Add changes" -a
           git push

